### ISSUE TITLE
May I ask how to modify “http://localhost:5173”

### ISSUE THREAD

**Issue by tiandaoyuxi** [AmyangXYZ/MiKaPo#3]
VITE v5.4.6  ready in 184 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

**Comment by AmyangXYZ** [comment]
I don't get your question. If you want to change port, use `npm run dev -- --host --port 12345`

**Comment by tiandaoyuxi** [comment]
THx！I want to modify the open IP address 0.0.0.0 for external network access it

**Comment by tiandaoyuxi** [comment]
D:\MiKaPo>npm run dev --host 0.0.0.0 --port 12345

> mikapo@0.0.0 dev
> vite 0.0.0.0 12345

Re-optimizing dependencies because vite config has changed
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

  VITE v5.4.6  ready in 303 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

**Comment by AmyangXYZ** [comment]
non run dev -- --host
